name: Release POS Printer

on:
  push:
    tags:
      - 'v*.*.*'
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Get version from tag
      id: get_version
      run: |
        $version = $env:GITHUB_REF -replace 'refs/tags/v', ''
        echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append
        echo "::set-output name=version::$version"
      shell: powershell
      
    - name: Update version.json
      run: |
        $versionInfo = @{
          version = "${{ env.VERSION }}"
          updated_at = Get-Date -Format "yyyy-MM-dd"
          description = "자동 배포 버전 ${{ env.VERSION }}"
        }
        $versionInfo | ConvertTo-Json -Depth 10 | Set-Content version.json -Encoding UTF8
      shell: powershell
      
    - name: Create release package
      run: |
        .\deployment_guide.ps1 -Version "${{ env.VERSION }}" -OutputPath ".\release"
      shell: powershell
      
    - name: Create ZIP archive
      run: |
        Compress-Archive -Path ".\release\*" -DestinationPath "POS_Printer_v${{ env.VERSION }}.zip" -Force
      shell: powershell
      
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./POS_Printer_v${{ env.VERSION }}.zip
        asset_name: POS_Printer_v${{ env.VERSION }}.zip
        asset_content_type: application/zip
        
    - name: Upload Installation Guide
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./INSTALLATION_GUIDE.md
        asset_name: INSTALLATION_GUIDE.md
        asset_content_type: text/markdown 